### ISSUE TITLE
CKAN does not boot if bad info are provided in config

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-azure-auth#2]
The ADFS logic performs some connections at boot time. 
If the connection fails (network issues, bad adfs params, ...), CKAN won't boot.

CKAN should perform calls to the authentication andpoint only when requested to.

**Comment by korotkin** [comment]
The request to the server is not removed.
Reason: In the received response presents url by which authentication should be performed
Added minor changes.  In case of an error  (4xx response)  the text with an error is displayed instead of the authorization URL.
